### PR TITLE
Fix folder_iam logic to use the correct updater

### LINKED ISSUE #708: fail to parse terraform 1.1.9 plan with `google_folder_iam_member` in a new folder
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

terraform-validator: v0.12.5
terraform-validator: v0.13.0
gcloud beta terraform vet: 2022.05.06

### Affected Resource(s)

* google_folder_iam_member

### Terraform Plan JSON

```hcl
resource "google_folder" "example" {
  display_name = "example"
  parent       = "folders/173181153785" # any valid folder or organization
}

resource "google_folder_iam_member" "editor" {
  folder  = google_folder.example.id
  role    = "roles/editor"
  member  = "user:john.doe@example.com"
}
```

```json
{
    "format_version": "1.0",
    "terraform_version": "1.1.9",
    "planned_values": {
        "root_module": {
            "resources": [
                {
                    "address": "google_folder.example",
                    "mode": "managed",
                    "type": "google_folder",
                    "name": "example",
                    "provider_name": "registry.terraform.io/hashicorp/google",
                    "schema_version": 0,
                    "values": {
                        "display_name": "example",
                        "parent": "folders/173181153785",
                        "timeouts": null
                    },
                    "sensitive_values": {}
                },
                {
                    "address": "google_folder_iam_member.editor",
                    "mode": "managed",
                    "type": "google_folder_iam_member",
                    "name": "editor",
                    "provider_name": "registry.terraform.io/hashicorp/google",
                    "schema_version": 0,
                    "values": {
                        "condition": [],
                        "member": "user:john.doe@example.com",
                        "role": "roles/editor"
                    },
                    "sensitive_values": {
                        "condition": []
                    }
                }
            ]
        }
    },
    "resource_changes": [
        {
            "address": "google_folder.example",
            "mode": "managed",
            "type": "google_folder",
            "name": "example",
            "provider_name": "registry.terraform.io/hashicorp/google",
            "change": {
                "actions": [
                    "create"
                ],
                "before": null,
                "after": {
                    "display_name": "example",
                    "parent": "folders/173181153785",
                    "timeouts": null
                },
                "after_unknown": {
                    "create_time": true,
                    "folder_id": true,
                    "id": true,
                    "lifecycle_state": true,
                    "name": true
                },
                "before_sensitive": false,
                "after_sensitive": {}
            }
        },
        {
            "address": "google_folder_iam_member.editor",
            "mode": "managed",
            "type": "google_folder_iam_member",
            "name": "editor",
            "provider_name": "registry.terraform.io/hashicorp/google",
            "change": {
                "actions": [
                    "create"
                ],
                "before": null,
                "after": {
                    "condition": [],
                    "member": "user:john.doe@example.com",
                    "role": "roles/editor"
                },
                "after_unknown": {
                    "condition": [],
                    "etag": true,
                    "folder": true,
                    "id": true
                },
                "before_sensitive": false,
                "after_sensitive": {
                    "condition": []
                }
            }
        }
    ],
    "configuration": {
        "root_module": {
            "resources": [
                {
                    "address": "google_folder.example",
                    "mode": "managed",
                    "type": "google_folder",
                    "name": "example",
                    "provider_config_key": "google",
                    "expressions": {
                        "display_name": {
                            "constant_value": "example"
                        },
                        "parent": {
                            "constant_value": "folders/173181153785"
                        }
                    },
                    "schema_version": 0
                },
                {
                    "address": "google_folder_iam_member.editor",
                    "mode": "managed",
                    "type": "google_folder_iam_member",
                    "name": "editor",
                    "provider_config_key": "google",
                    "expressions": {
                        "folder": {
                            "references": [
                                "google_folder.example.id",
                                "google_folder.example"
                            ]
                        },
                        "member": {
                            "constant_value": "user:john.doe@example.com"
                        },
                        "role": {
                            "constant_value": "roles/editor"
                        }
                    },
                    "schema_version": 0
                }
            ]
        }
    }
}
```

### Debug Output

```
unknown flag: --verbose
```
### Expected Behavior

plan to be parsed without violations

### Actual Behavior

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraform-validator/converters/google/resources.NewProjectIamUpdater(0x4474578, 0xc0009615c0, 0xc00072c700, 0xc0004c5a40, 0x1100000000000002, 0xc00007a800, 0x0)
        /Users/stephenrlewis/projects/terraform-validator/converters/google/resources/iam_project.go:28 +0x145
github.com/GoogleCloudPlatform/terraform-validator/converters/google/resources.fetchIamPolicy(0x3fecb18, 0x4474578, 0xc0009615c0, 0xc00072c700, 0x3e61286, 0x30, 0x3e46179, 0x2a, 0x0, 0x0, ...)
        /Users/stephenrlewis/projects/terraform-validator/converters/google/resources/iam_helpers.go:199 +0x94
github.com/GoogleCloudPlatform/terraform-validator/converters/google/resources.FetchFolderIamPolicy(0x4474578, 0xc0009615c0, 0xc00072c700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/stephenrlewis/projects/terraform-validator/converters/google/resources/folder_iam.go:92 +0xee
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).addCreateOrUpdateOrNoop(0xc000b66000, 0xc00077f950, 0x1b, 0x0)
        /Users/stephenrlewis/projects/terraform-validator/converters/google/convert.go:311 +0x8b3
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).AddResourceChanges(0xc000b66000, 0xc000176480, 0x69, 0x8d, 0x69, 0x8d)
        /Users/stephenrlewis/projects/terraform-validator/converters/google/convert.go:214 +0x538
github.com/GoogleCloudPlatform/terraform-validator/tfgcv.ReadPlannedAssets(0x4430d78, 0xc00004e068, 0x7ffdd08d7cad, 0xe, 0x7ffdd08d7ce7, 0x16, 0x0, 0x0, 0x1ffffffffff0000, 0xc00011a840, ...)
        /Users/stephenrlewis/projects/terraform-validator/tfgcv/planned_assets.go:58 +0x16a
github.com/GoogleCloudPlatform/terraform-validator/cmd.(*validateOptions).run(0xc00011a6c0, 0x7ffdd08d7cad, 0xe, 0x0, 0x0)
        /Users/stephenrlewis/projects/terraform-validator/cmd/validate.go:115 +0x7fa
github.com/GoogleCloudPlatform/terraform-validator/cmd.newValidateCmd.func2(0xc000631400, 0xc0007296e0, 0x1, 0x3, 0x0, 0x0)
        /Users/stephenrlewis/projects/terraform-validator/cmd/validate.go:78 +0x50
github.com/spf13/cobra.(*Command).execute(0xc000631400, 0xc000729650, 0x3, 0x3, 0xc000631400, 0xc000729650)
        /Users/stephenrlewis/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000630a00, 0xc0007292c0, 0x0, 0x0)
        /Users/stephenrlewis/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/stephenrlewis/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/GoogleCloudPlatform/terraform-validator/cmd.Execute()
        /Users/stephenrlewis/projects/terraform-validator/cmd/root.go:101 +0xf4
main.main()
        /Users/stephenrlewis/projects/terraform-validator/main.go:30 +0xa6
```

### Steps to Reproduce

1. `terraform plan -out example.tfplan`
2. `terraform show -json example.tfplan > example.json`
3. `terraform-validator validate example.json --policy-path=<path-to-policy-library> --project=<VALID-EXISTING-PROJECT>`

### Important Factoids

Plan generated with **terraform 1.1.9**

### References

* #0000

### PR DESCRIPTION
**Pull request by roaks3**
This change fixes the `google_folder_iam_member` resource by using the correct updater in our `folder_iam` logic. It also introduces tests for the `google_folder_iam_member` to prevent regressions.

Fixes #708 
b/233071873

### CODE REVIEW

**Comment by roaks3** [comment]
@melinath I'm not sure if you have a better idea of what's going wrong, but my latest attempt at getting these tests working was to introduce a new folder, and I was expecting the test to work like the storage bucket from this example: https://github.com/GoogleCloudPlatform/terraform-validator/pull/218. However, I'm still getting errors when they run. My suspicion is that I'm doing something wrong with the placeholders, or perhaps folders are somehow handled differently than storage buckets.

**Comment by roaks3** [comment]
Ahh, after seeing the unit test failure already, now I'm wondering if the issue here is that `google_folder` itself is not a supported resource (where `google_storage_bucket` is from the other example)

**Review by melinath — CHANGES_REQUESTED** [review]
google_folder isn't supported, but that won't have any impact on whether the related iam resource can be validated, so you should be good from that perspective!

It looks like the fatal error you're getting is:

```
converting TF resource to CAI: getting resource ancestry or parent failed: folder id not found in terraform data
```

That's coming from [ancestrymanager.go](https://github.com/GoogleCloudPlatform/terraform-validator/blob/f7f2796d3ad0009ee8887040ba7055d773640c38/ancestrymanager/ancestrymanager.go#L137) - basically it means that the folder id is `(known after apply)`. The workaround is to "hardcode" the folder id as a known value using the `{{.FolderID}}` variable.

It looks like we do this currently for folder-level organization policies, so you may be able to base your work off of that: https://github.com/GoogleCloudPlatform/terraform-validator/blob/f7f2796d3ad0009ee8887040ba7055d773640c38/testdata/templates/example_folder_organization_policy.tf#L30

**Comment by roaks3** [comment]
@melinath if you take a look at the initial commit in this PR, I had tried using the `{{.FolderID}}`, but ran into the other issue we had talked about where there are other permissions on the folder already. Here is the integration test error from that commit: https://pantheon.corp.google.com/cloud-build/builds/82d19c48-b300-43bc-b494-28c78c2aed43?project=cloud-foundation-cicd.

I'm happy to shift toward a solution using the folder provided by the user, but can you provide any insight on how to get around the existing permissions problem?

**Comment by melinath** [comment]
@roaks3 ah, gotcha! Thanks for letting me know. I'll look into that and see if we already have a workaround.

**Comment by melinath** [comment]
Okay - so, it looks like for iam binding and iam member, we use special comparison functions to only check the parts we care about: https://github.com/GoogleCloudPlatform/terraform-validator/blob/f7f2796d3ad0009ee8887040ba7055d773640c38/test/cli_test.go#L63

For iam_policy, it shouldn't have any issues because it's fully authoritative.

Once you get to the magic modules side - I believe that if you add the folder tests as an explicit test in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/validator/tests/source/cli_test.go.erb, it should automatically exclude them from the autogenerated list.

Relatedly: As long as you're working on this, could you add tests for iam binding and iam policy as well to make sure there aren't any issues we're missing there?

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
