### PR TITLE
Add an no-op ancestry manager

### PR DESCRIPTION
**Pull request by iyabchen**
Add an no op ancestry manager, so internal code can use this for testing, and no need to implement the ancestry manager interface. The interface will need to be modified.

### CODE REVIEW

**Comment by yukinying** [comment]
Any possibliity to add unit tests, here or via some upper caller?

**Review by yukinying — APPROVED** [review]
LGTM, comment added above.

**Comment by iyabchen** [comment]
> Any possibliity to add unit tests, here or via some upper caller?

Just added a change to modify an existing test case to use the noop ancestry manager.

**Review by melinath — APPROVED** [review]
using noop ancestry manager there seems reasonable to me.

**Pull request merged**
