### PR TITLE
Log warning for assets that did not return a value for ID field

### PR DESCRIPTION
**Pull request by c2thorn**
Closes https://github.com/GoogleCloudPlatform/terraform-validator/issues/216

Tested with a tfjson plan identical to the one in the issue.

### CODE REVIEW

**Comment by c2thorn** [comment]
Looks like there's a panic caused by https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/709

**Review by melinath — CHANGES_REQUESTED** [review]
LGTM as an implementation; would it be possible to add an integration test? I assume we would need to avoid using a module, but perhaps we could explicitly set up the underlying relationship that caused the crash?

Adding tests for resources is documented a bit here: https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/docs/add_new_resource.md#2-terraform-validator

I imagine it would be similar to the example_storage_bucket_iam_member tests.

**Comment by melinath** [comment]
The tests are passing for both me & @c2thorn locally. This is because the results of `convert` are not fully deterministic.

We use [`map[string]Asset`](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/converters/google/convert.go#L168) to store assets internally; Golang maps are not ordered. So when we pull out the list of assets, we order them by [Asset Name](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/converters/google/convert.go#L342) - for example, `//storage.googleapis.com/placeholder-c2WD8F2q` (the last bit is generated by terraform-google-conversion).

In test runs, we then "normalize" assets for comparison, which replaces `placeholder-.*` with `placeholder-foobar` so that we can have passing tests even with randomly-generated asset names. This obscures the fact that the assets were first sorted by their random name (which means that the results are not deterministic even though they're sorted by name.)

**Comment by melinath** [comment]
It's odd that it seems to pass consistently for me locally though... :-/

**Comment by melinath** [comment]
Okay, so if I am just running the one test, it always gets the same values for the random placeholder strings. This is almost certainly because we use [`rand.Intn`](https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/a96c3de41339f92e9fb31b5ac62ec9b350484925/google/cai.go#L102) to generate the placeholder values, which relies on Golang's pseudo-random builtins, which always start with the [same randomness seed](https://golang.org/pkg/math/rand/#Seed).

So, the full test suite is probably failing because it's preceded by a bunch of `randIntn` calls, resulting in output that happens to be different than what we get just running that test. We're lucky we caught this now!

On the plus side, this means that if we can find a thread-safe way to reset the seed before each test, we could make all tests deterministic with regard to their generated strings. If that doesn't work we'll have to find some other solution.

**Comment by c2thorn** [comment]
@melinath Moved the test failure to its own issue, skipped the test and rebased.

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
