### PR TITLE
[WIP] Update conversion dependencies

### PR DESCRIPTION
**Pull request by morgante**
Updated `vendor/` directory.

### CODE REVIEW

**Comment by briantkennedy** [comment]
looks like this needs a rebase

**Comment by yukinying** [comment]
This probably will not work until all direct API calls are removed, OR the ConfigureBasePaths function is cloned from https://github.com/terraform-providers/terraform-provider-google/blob/master/google/provider.go#L440 to https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/master/google.

**Comment by yukinying** [comment]
The pull request on removing direct API calls are created in https://github.com/GoogleCloudPlatform/magic-modules/pull/2132. Once it gets merged, I believe GoogleCloudPlatform/terraform-google-conversion will have a pull request that would take those changes. I suggest pulling in those changes as a whole instead.

**Comment by yukinying** [comment]
I opened an issue on magic-modules to ask for a fix: https://github.com/GoogleCloudPlatform/magic-modules/issues/2133

**Comment by yukinying** [comment]
GoogleCloudPlatform/magic-modules#2133 is fixed, but there is another issue which I reported via https://github.com/GoogleCloudPlatform/magic-modules/issues/2234.

**Comment by yukinying** [comment]
I believe this pull request is no longer needed as the dependencies are already updated.

**Pull request closed without merging**
