### PR TITLE
add handling of empty versioning and cors in storage bucket from TGC

### PR DESCRIPTION
**Pull request by daniel-cit**
This PR Closes https://github.com/GoogleCloudPlatform/terraform-validator/issues/201

The bump in the `terraform-google-conversion` version pull from terraform-google-conversion this fix:

https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/661/commits/c97b59312fd5af32c30d50f9f866978a52ea4ca3

### CODE REVIEW

**Comment by daniel-cit** [comment]
Original Magic Modules PR:
https://github.com/GoogleCloudPlatform/magic-modules/pull/4608

**Review by melinath — CHANGES_REQUESTED** [review]
I'm down to do this upgrade; however, it would be great to add a test that would have caught this issue to that we don't run into it in the future.

**Comment by daniel-cit** [comment]
@melinath I will add a new test for it

**Comment by melinath** [comment]
I don't know if it's at all relevant but just in case, we had a similar error from https://github.com/GoogleCloudPlatform/terraform-validator/pull/195 recently that ended up needing a newer version of terraform-provider-google rather than a change to an expander (which I only realized after doing the change to the expander). If that ends up being the case here as well (i.e. if this ends up needing tpg-3.61.0) I will be able to do that upgrade after the release on Monday.

**Comment by daniel-cit** [comment]
@melinath I don't think it is the case here, if we look at how the hand written code handles empty values we can se that there are 4 properties that cloud have this issue: `cors` , `encryption`, `versioning`, and  `website` 

```json
...
"cors": [
    {}
],
...
"encryption": [
    {}
],
...
"versioning": [
    {}
],
"website": [
    {}
]
....
```

`encryption`  and  `website` had the same type of fix but the ones in this PR did not.

**Comment by daniel-cit** [comment]
Unit test result without fix::

```
--- FAIL: TestAddStorageModuleAfterUnknown (0.00s)
panic: interface conversion: interface {} is nil, not map[string]interface {} [recovered]
        panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 21 [running]:
testing.tRunner.func1(0xc000272300)
        /usr/lib/go-1.13/src/testing/testing.go:874 +0x3a3
panic(0x2846120, 0xc0004ac4e0)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/GoogleCloudPlatform/terraform-google-conversion/google.expandBucketVersioning(...)
        /home/dandrade/go/pkg/mod/github.com/!google!cloud!platform/terraform-google-conversion@v0.0.0-20210318171059-9ab40040d220/google/storage_bucket.go:163
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketApiObject(0x32ce880, 0xc0004ac300, 0xc0005d8600, 0x2cf0140, 0x21, 0xc00055a390)
        /home/dandrade/go/pkg/mod/github.com/!google!cloud!platform/terraform-google-conversion@v0.0.0-20210318171059-9ab40040d220/google/storage_bucket.go:67 +0x110c
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketCaiObject(0x32ce880, 0xc0004ac300, 0xc0005d8600, 0x15, 0xc00059a0a0, 0xc0001b4280, 0x2ccf52d, 0x15)
        /home/dandrade/go/pkg/mod/github.com/!google!cloud!platform/terraform-google-conversion@v0.0.0-20210318171059-9ab40040d220/google/storage_bucket.go:24 +0xad
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).addCreateOrUpdate(0xc000575580, 0xc000312870, 0x0, 0x0)
        /home/dandrade/repos/terraform-validator/converters/google/convert.go:278 +0x1e1
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).AddResourceChanges(0xc000575580, 0xc000175e88, 0x1, 0x1, 0x0, 0x0)
        /home/dandrade/repos/terraform-validator/converters/google/convert.go:203 +0x4dc
github.com/GoogleCloudPlatform/terraform-validator/converters/google.TestAddStorageModuleAfterUnknown(0xc000272300)
        /home/dandrade/repos/terraform-validator/converters/google/convert_test.go:434 +0x13db
testing.tRunner(0xc000272300, 0x2ddd9a0)
        /usr/lib/go-1.13/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
        /usr/lib/go-1.13/src/testing/testing.go:960 +0x350
FAIL    github.com/GoogleCloudPlatform/terraform-validator/converters/google    0.076s
ok      github.com/GoogleCloudPlatform/terraform-validator/test (cached)
ok      github.com/GoogleCloudPlatform/terraform-validator/tfgcv        (cached)
ok      github.com/GoogleCloudPlatform/terraform-validator/tfplan       (cached)
FAIL
make: *** [Makefile:10: test] Error 1
```

Unit test result with fix:

```
# Skip integration tests in ./test/ using -short flag
GO111MODULE=on go test -short ./...
?       github.com/GoogleCloudPlatform/terraform-validator      [no test files]
ok      github.com/GoogleCloudPlatform/terraform-validator/ancestrymanager      (cached)
?       github.com/GoogleCloudPlatform/terraform-validator/cmd  [no test files]
ok      github.com/GoogleCloudPlatform/terraform-validator/converters/google    0.118s
ok      github.com/GoogleCloudPlatform/terraform-validator/test (cached)
ok      github.com/GoogleCloudPlatform/terraform-validator/tfgcv        (cached)
ok      github.com/GoogleCloudPlatform/terraform-validator/tfplan       (cached)
```

**Comment by daniel-cit** [comment]
**Regrading the usage of a unit test insted of an integration test**

To be able to reproduce this error using a integration test (using a real `tf` file), I would need to use an external module call, so that terraform can "solve" the unknown value for the versioning.

Sample tf file

```terraform
locals {
  name = random_string.bucket_name.result
}

resource "random_string" "bucket_name" {
  length  = 5
  upper   = false
  number  = true
  lower   = true
  special = false
}

module "storage" {
  source     = "terraform-google-modules/cloud-storage/google"
  version    = "= 1.7.2"
  project_id = "tst-project"
  location   = "US"
  names      = [local.name]
  prefix     = "tst-bucket"
  versioning = { (local.name) = true }
}
```

Trying to run this file in the integration test I always get this error:


```
            Error: Failed to download module

            Could not download module "storage"
            (example_unknown_storage_values_remote_module.tf:42) source code from
            "git::https://github.com/terraform-google-modules/terraform-google-cloud-storage?ref=v1.7.2":
            error downloading
            'https://github.com/terraform-google-modules/terraform-google-cloud-storage?ref=v1.7.2':
            git must be available and on the PATH.


            stdout=Initializing modules...
            Downloading terraform-google-modules/cloud-storage/google 1.7.2 for storage...
```  

but in nthe environment I am testing
**git is available**
and
**git is on the PATH**

I got this error both in my machine and in cloud shell.

if if try to do a normal `terraform plan` with the same code I got:

```console
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # random_string.bucket_name will be created
  + resource "random_string" "bucket_name" {
      + id          = (known after apply)
      + length      = 5
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + result      = (known after apply)
      + special     = false
      + upper       = false
    }

  # module.storage.google_storage_bucket.buckets[0] will be created
  + resource "google_storage_bucket" "buckets" {
      + bucket_policy_only          = (known after apply)
      + force_destroy               = (known after apply)
      + id                          = (known after apply)
      + labels                      = (known after apply)
      + location                    = "US"
      + name                        = (known after apply)
      + project                     = "tst-project"
      + self_link                   = (known after apply)
      + storage_class               = "MULTI_REGIONAL"
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)

      + cors {
          + max_age_seconds = (known after apply)
          + method          = (known after apply)
          + origin          = (known after apply)
          + response_header = (known after apply)
        }

      + encryption {
          + default_kms_key_name = (known after apply)
        }

      + versioning {
          + enabled = (known after apply)
        }

      + website {
          + main_page_suffix = (known after apply)
          + not_found_page   = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```


If I try to use a local module or if I try to inline the module code I get a blocking error:

```console
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Invalid for_each argument

  on terraform-google-cloud-storage/main.tf line 33, in resource "google_storage_bucket" "buckets":
  33:   for_each = local.names_set

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

`names_set` is crated from the array with the random value for the name.

https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/9f6085e671eea558585f4c5027bd94f1bcdd4a11/main.tf#L33

```terraform

locals {
...
  names_set    = toset(var.names)
}
...
resource "google_storage_bucket" "buckets" {
  for_each = local.names_set
...
  versioning {
    enabled = lookup(
      var.versioning,
      lower(each.value),
      false,
    )
  }
...
````
```
 

Because of these issues I choose to do an unit test for this fix.

**Review by melinath — APPROVED** [review]
Thanks for the detail - sorry the integration test path didn't work out. A unit test is totally good too. :-)

**Pull request merged**
