### PR TITLE
Fix project organization policy

### PR DESCRIPTION
**Pull request by daniel-cit**
Fixes https://github.com/GoogleCloudPlatform/terraform-validator/issues/213

also this PR adds `"example_project_organization_policy"` to the list of integration tests executed by the `cli_test`

- [x] Fix out of sync current time issue in integration build

### CODE REVIEW

**Comment by daniel-cit** [comment]
@melinath  could you PTAL ?

**Comment by daniel-cit** [comment]
I still need to find a way to do the integration test with the `update_time` field, since the values may be out of sync by a few seconds:

```
Step #2 - "test-integration":         --- FAIL: TestCLI/v=0.12/tf=example_project_organization_policy/offline=true/cmd=convert (0.13s)
Step #2 - "test-integration":             cli_test.go:386: === STDOUT of /workspace/bin/terraform-validator convert --project REDACTED-PROJECT-ID --offline --ancestry organization/12345/folder/67890 example_project_organization_policy.tfplan.json ===
Step #2 - "test-integration":             cli_test.go:387: [{"name":"//cloudresourcemanager.googleapis.com/projects/REDACTED-PROJECT-ID","asset_type":"cloudresourcemanager.googleapis.com/Project","ancestry_path":"organization/12345/folder/67890/project/REDACTED-PROJECT-ID","org_policy":[{"constraint":"constraints/compute.disableSerialPortAccess","boolean_policy":{"enforced":true},"update_time":"2021-04-14T05:50:00Z"},{"constraint":"constraints/iam.disableServiceAccountCreation","restore_default":{},"update_time":"2021-04-14T05:50:00Z"},{"constraint":"constraints/serviceuser.services","list_policy":{"all_values":1},"update_time":"2021-04-14T05:50:00Z"}]}]
Step #2 - "test-integration":                 
Step #2 - "test-integration":             cli_test.go:185: 
Step #2 - "test-integration":                 	Error Trace:	cli_test.go:185
Step #2 - "test-integration":                 	            				cli_test.go:281
Step #2 - "test-integration":                 	            				cli_test.go:164
Step #2 - "test-integration":                 	Error:      	Not equal: 
Step #2 - "test-integration":                 	            	expected: []interface {}{map[string]interface {}{"ancestry_path":"organization/12345/folder/67890/project/REDACTED-PROJECT-ID", "asset_type":"cloudresourcemanager.googleapis.com/Project", "name":"//cloudresourcemanager.googleapis.com/projects/REDACTED-PROJECT-ID", "org_policy":[]interface {}{map[string]interface {}{"boolean_policy":map[string]interface {}{"enforced":true}, "constraint":"constraints/compute.disableSerialPortAccess", "update_time":"2021-04-14T05:49:00Z"}, map[string]interface {}{"constraint":"constraints/iam.disableServiceAccountCreation", "restore_default":map[string]interface {}{}, "update_time":"2021-04-14T05:49:00Z"}, map[string]interface {}{"constraint":"constraints/serviceuser.services", "list_policy":map[string]interface {}{"all_values":1}, "update_time":"2021-04-14T05:49:00Z"}}}}
Step #2 - "test-integration":                 	            	actual  : []interface {}{map[string]interface {}{"ancestry_path":"organization/12345/folder/67890/project/REDACTED-PROJECT-ID", "asset_type":"cloudresourcemanager.googleapis.com/Project", "name":"//cloudresourcemanager.googleapis.com/projects/REDACTED-PROJECT-ID", "org_policy":[]interface {}{map[string]interface {}{"boolean_policy":map[string]interface {}{"enforced":true}, "constraint":"constraints/compute.disableSerialPortAccess", "update_time":"2021-04-14T05:50:00Z"}, map[string]interface {}{"constraint":"constraints/iam.disableServiceAccountCreation", "restore_default":map[string]interface {}{}, "update_time":"2021-04-14T05:50:00Z"}, map[string]interface {}{"constraint":"constraints/serviceuser.services", "list_policy":map[string]interface {}{"all_values":1}, "update_time":"2021-04-14T05:50:00Z"}}}}
Step #2 - "test-integration":                 	            	
Step #2 - "test-integration":                 	            	Diff:
Step #2 - "test-integration":                 	            	--- Expected
Step #2 - "test-integration":                 	            	+++ Actual
Step #2 - "test-integration":                 	            	@@ -11,3 +11,3 @@
Step #2 - "test-integration":                 	            	     (string) (len=10) "constraint": (string) (len=43) "constraints/compute.disableSerialPortAccess",
Step #2 - "test-integration":                 	            	-    (string) (len=11) "update_time": (string) (len=20) "2021-04-14T05:49:00Z"
Step #2 - "test-integration":                 	            	+    (string) (len=11) "update_time": (string) (len=20) "2021-04-14T05:50:00Z"
Step #2 - "test-integration":                 	            	    },
Step #2 - "test-integration":                 	            	@@ -17,3 +17,3 @@
Step #2 - "test-integration":                 	            	     },
Step #2 - "test-integration":                 	            	-    (string) (len=11) "update_time": (string) (len=20) "2021-04-14T05:49:00Z"
Step #2 - "test-integration":                 	            	+    (string) (len=11) "update_time": (string) (len=20) "2021-04-14T05:50:00Z"
Step #2 - "test-integration":                 	            	    },
Step #2 - "test-integration":                 	            	@@ -24,3 +24,3 @@
Step #2 - "test-integration":                 	            	     },
Step #2 - "test-integration":                 	            	-    (string) (len=11) "update_time": (string) (len=20) "2021-04-14T05:49:00Z"
Step #2 - "test-integration":                 	            	+    (string) (len=11) "update_time": (string) (len=20) "2021-04-14T05:50:00Z"
Step #2 - "test-integration":                 	            	    }
```

**Comment by melinath** [comment]
Are we actually using the update time for anything? I might prefer to either remove it or (if we can't remove it) put in a sentinel value rather than the current time.

**Comment by melinath** [comment]
It looks like project organization was added in https://github.com/GoogleCloudPlatform/terraform-validator/pull/157 - @rdayama-eng do you have any insight here?

**Comment by rdayama-eng** [comment]
Yes, this was added to support project organization policy.


•  Rohit Dayama

•  Software Engineer

•  ***@***.***

•  Bangalore

**Comment by melinath** [comment]
@rdayama-eng yes, could you elaborate? For example, is update time actually needed? it doesn't look like it's being pulled from the terraform plan, so could we safely not even set it, or set it to a sentinel value?

**Comment by rdayama-eng** [comment]
It is not used anywhere, but we just wanted org policy to be consistent
with CAI asset


•  Rohit Dayama

•  Software Engineer

•  ***@***.***

•  Bangalore

**Comment by daniel-cit** [comment]
We are now using a fixed value for the `update_time` and the original structure of the object was preserved with the addition of custom marshal and unmarshal code for the timestamp conversion to/from string.

**Comment by daniel-cit** [comment]
@melinath is this current solution fine or should we remove the `update_time` field?

**Review by melinath — APPROVED** [review]
LGTM - thanks for fixing this!

**Pull request merged**
