### PR TITLE
add compute forwarding rule support

### PR DESCRIPTION
**Pull request by ericyz**

### CODE REVIEW

**Comment by ericyz** [comment]
Hi @melinath , this PR is ready for review

**Review by melinath — CHANGES_REQUESTED** [review]
LGTM in general but integration tests are failing:

```
--- FAIL: TestCLI/v=0.12/tf=example_compute_forwarding_rule/offline=true/cmd=convert (0.13s)
    cli_test.go:360: === STDOUT of /workspace/bin/terraform-validator convert --project ci-terraform-validator-fef2 --offline --ancestry organization/12345/folder/67890 example_compute_forwarding_rule.tfplan.json ===
    cli_test.go:361: [{"name":"//compute.googleapis.com/projects/ci-terraform-validator-fef2/regions/australia-southeast1/forwardingRules/test-forwarding-rule","asset_type":"compute.googleapis.com/ForwardingRule","ancestry_path":"organization/12345/folder/67890/project/ci-terraform-validator-fef2","resource":{"version":"v1","discovery_document_uri":"https://www.googleapis.com/discovery/v1/apis/compute/v1/rest","discovery_name":"ForwardingRule","parent":"//cloudresourcemanager.googleapis.com/projects/ci-terraform-validator-fef2","data":{"IPProtocol":"TCP","allowGlobalAccess":false,"backendService":"projects/ci-terraform-validator-fef2/regions/australia-southeast1/test-backend-service-id","loadBalancingScheme":"INTERNAL_MANAGED","name":"test-forwarding-rule","portRange":"80","region":"projects/ci-terraform-validator-fef2/global/regions/australia-southeast1"}}}]
        
    cli_test.go:153: 
        	Error Trace:	cli_test.go:153
        	            				cli_test.go:255
        	            				cli_test.go:132
        	Error:      	Not equal: 
        	            	expected: []interface {}{map[string]interface {}{"ancestry_path":"organization/12345/folder/67890/project/ci-terraform-validator-fef2", "asset_type":"compute.googleapis.com/ForwardingRule", "name":"//compute.googleapis.com/projects/ci-terraform-validator-fef2/regions/australia-southeast1/forwardingRules/test-forwarding-rule", "resource":map[string]interface {}{"data":map[string]interface {}{"IPProtocol":"TCP", "allowGlobalAccess":false, "backendService":"https://compute.googleapis.com/compute/v1/projects/ci-terraform-validator-fef2/regions/australia-southeast1/test-backend-service-id", "loadBalancingScheme":"INTERNAL_MANAGED", "name":"test-forwarding-rule", "portRange":"80", "region":"projects/ci-terraform-validator-fef2/global/regions/australia-southeast1"}, "discovery_document_uri":"https://www.googleapis.com/discovery/v1/apis/compute/v1/rest", "discovery_name":"ForwardingRule", "parent":"//cloudresourcemanager.googleapis.com/projects/ci-terraform-validator-fef2", "version":"v1"}}}
        	            	actual  : []interface {}{map[string]interface {}{"ancestry_path":"organization/12345/folder/67890/project/ci-terraform-validator-fef2", "asset_type":"compute.googleapis.com/ForwardingRule", "name":"//compute.googleapis.com/projects/ci-terraform-validator-fef2/regions/australia-southeast1/forwardingRules/test-forwarding-rule", "resource":map[string]interface {}{"data":map[string]interface {}{"IPProtocol":"TCP", "allowGlobalAccess":false, "backendService":"projects/ci-terraform-validator-fef2/regions/australia-southeast1/test-backend-service-id", "loadBalancingScheme":"INTERNAL_MANAGED", "name":"test-forwarding-rule", "portRange":"80", "region":"projects/ci-terraform-validator-fef2/global/regions/australia-southeast1"}, "discovery_document_uri":"https://www.googleapis.com/discovery/v1/apis/compute/v1/rest", "discovery_name":"ForwardingRule", "parent":"//cloudresourcemanager.googleapis.com/projects/ci-terraform-validator-fef2", "version":"v1"}}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -9,3 +9,3 @@
        	            	     (string) (len=17) "allowGlobalAccess": (bool) false,
        	            	-    (string) (len=14) "backendService": (string) (len=131) "https://compute.googleapis.com/compute/v1/projects/ci-terraform-validator-fef2/regions/australia-southeast1/test-backend-service-id",
        	            	+    (string) (len=14) "backendService": (string) (len=89) "projects/ci-terraform-validator-fef2/regions/australia-southeast1/test-backend-service-id",
        	            	     (string) (len=19) "loadBalancingScheme": (string) (len=16) "INTERNAL_MANAGED",
```

You can run the integration tests as described here: https://github.com/GoogleCloudPlatform/terraform-validator/blob/088f90a4bc3611fe05d9156ce00ea569ddd75c18/README.md#testing

Let me know if you run into any issues!

**Comment by ericyz** [comment]
Hi @melinath , the link you attached shows a 404 to me. (https://github.com/GoogleCloudPlatform/terraform-validator/blob/tpg-8431-contributing/README.md#testing)

**Comment by melinath** [comment]
@ericyz (sorry about the broken link; fixed)

It looks like the offline mode was originally added in https://github.com/GoogleCloudPlatform/terraform-validator/pull/73, partially to allow unit tests to run without connecting to the GCP API. I'm not sure if there were other reasons. Maybe @morgante could shed some light? I could imagine it being useful for users who want to run terraform-validator in an environment where they don't have GCP API access for whatever reason.

If the expected value is different in the offline version (but in a predictable way) it might be nice to find a way to split out the expected result for the offline / online versions. We do also have the option of skipping tests that can't run in offline mode, but  I would generally prefer to only use that in cases that can't be addressed, or to temporarily skip tests until we can fix them.

**Comment by morgante** [comment]
> It looks like the offline mode was originally added in #73, partially to allow unit tests to run without connecting to the GCP API. I'm not sure if there were other reasons. Maybe @morgante could shed some light? I could imagine it being useful for users who want to run terraform-validator in an environment where they don't have GCP API access for whatever reason.

Yes, the other use case is running TFV in sandboxed environments where network access is forbidden (including in google3).

**Comment by ericyz** [comment]
Not a big fan to temporarily skip the test for offline mode, but it would require some handwriting in the magic module or we split out the test cases for online and offline. Concerning time, I might come back to this when time allowed.

**Review by melinath — APPROVED** [review]
LGTM

**Comment by melinath** [comment]
There are a bunch of extraneous commits in the history now but it all seems to be stuff that's also on master so I think it should be fine.

**Pull request merged**
