### PR TITLE
make the tool support only one selected version of Terraform

### LINKED ISSUE #69: Support a single version Terraform at a time, possible via a global variable and build tricks.
go.mod requires github.com/hashicorp/terraform v0.11.11 thus blocking updates 

This is related to issue #68. In order to update the dependency terraform-providers/terraform-provider-google to the latest version, dependency on hashicorp/terraform needs to be upgraded to v0.12+. However, the code here is still using hashicorp/terraform v0.11. I tried upgraded to v0.12 and it would complaint about missing struct `terraform.Plan`, which seems to be removed from v0.12.

Without terraform-providers/terraform-provider-google be upgraded, pulling changes on GoogleCloudPlatform/terraform-google-conversion would create panic (as described in #68).

// cc @morgante @t12g

### PR DESCRIPTION
**Pull request by yukinying**
This should fix #69 and address https://github.com/GoogleCloudPlatform/terraform-validator/pull/70#issuecomment-526360935.

### CODE REVIEW

**Comment by yukinying** [comment]
Yes, all the make command need to be run with the `prepare-v11` directive as the build tag needs to be provided. I have updated the README.md for that. I think moving forward there should be a better way to detect the build tag (probably by greping the TF version in go.mod in the makefile).

```
$ make prepare-v11 test-integration
Prepare the environment for TF v0.11
cp go_tf_0_11.mod go.mod
go test -tags="tf_0_11" -v ./test
=== RUN   TestConvert
=== RUN   TestConvert/disk/TF_0.11
=== RUN   TestConvert/project/TF_0.11
=== RUN   TestConvert/project_billing_info/TF_0.11
=== RUN   TestConvert/firewall/TF_0.11
=== RUN   TestConvert/instance/TF_0.11
=== RUN   TestConvert/bucket/TF_0.11
=== RUN   TestConvert/sql/TF_0.11
=== RUN   TestConvert/firewall/TF_0.11#01
=== RUN   TestConvert/validate/always_violate/TF_0.11
--- PASS: TestConvert (6.39s)
    --- PASS: TestConvert/disk/TF_0.11 (0.00s)
    --- PASS: TestConvert/project/TF_0.11 (0.00s)
    --- PASS: TestConvert/project_billing_info/TF_0.11 (0.00s)
    --- PASS: TestConvert/firewall/TF_0.11 (0.00s)
    --- PASS: TestConvert/instance/TF_0.11 (0.00s)
    --- PASS: TestConvert/bucket/TF_0.11 (0.00s)
    --- PASS: TestConvert/sql/TF_0.11 (0.00s)
    --- PASS: TestConvert/firewall/TF_0.11#01 (0.00s)
    --- PASS: TestConvert/validate/always_violate/TF_0.11 (1.16s)
PASS
ok  	github.com/GoogleCloudPlatform/terraform-validator/test	6.591s
```

**Comment by yukinying** [comment]
I will provide the logic on grepping go.mod on next pull request. It needs to be coupled with the pull request on updating dependencies as the version of terraform will be available inside go.mod.

**Comment by yukinying** [comment]
@morgante , the test procedure has been updated so integration test would work. Please also check #72 that has the dependencies updated (and integration test also work there).

**Comment by morgante** [comment]
Unfortunately tests seem to be timing out/taking an extremely long time to complete. Any ideas what might be causing this?

**Comment by yukinying** [comment]
Are you referring to `TestConvert (6.39s)`? I believe the time are taken in the setup phase that converts `.tf` file into `.tfplan`? Since TestConvert depends on running `terraform` directly in a shell, I believe `terraform` may need extra setup time if it needs to fetch updated dependencies, such as the new version of google provider.

**Comment by yukinying** [comment]
The master branch also takes quite long time to finish integration test, so I would bet we may rule out this pull request adding time required for completing the test.

Below is a output trace of running integration test in master branch.
```
$ make build test-integration
GO111MODULE=on go build -ldflags "-X github.com/GoogleCloudPlatform/terraform-validator/tfgcv.buildVersion=`date +%Y-%m-%d`" -mod=vendor -o ./bin/terraform-validator
go test -v ./test
=== RUN   TestConvert
=== RUN   TestConvert/disk/TF_0.11
=== RUN   TestConvert/project/TF_0.11
=== RUN   TestConvert/project_billing_info/TF_0.11
=== RUN   TestConvert/firewall/TF_0.11
=== RUN   TestConvert/instance/TF_0.11
=== RUN   TestConvert/bucket/TF_0.11
=== RUN   TestConvert/sql/TF_0.11
=== RUN   TestConvert/firewall/TF_0.11#01
=== RUN   TestConvert/validate/always_violate/TF_0.11
=== RUN   TestConvert/disk/TF_0.12
=== RUN   TestConvert/project/TF_0.12
=== RUN   TestConvert/project_billing_info/TF_0.12
=== RUN   TestConvert/firewall/TF_0.12
=== RUN   TestConvert/instance/TF_0.12
=== RUN   TestConvert/bucket/TF_0.12
=== RUN   TestConvert/sql/TF_0.12
=== RUN   TestConvert/firewall/TF_0.12#01
=== RUN   TestConvert/validate/always_violate/TF_0.12
--- PASS: TestConvert (8.84s)
    --- PASS: TestConvert/disk/TF_0.11 (0.00s)
    --- PASS: TestConvert/project/TF_0.11 (0.00s)
    --- PASS: TestConvert/project_billing_info/TF_0.11 (0.00s)
    --- PASS: TestConvert/firewall/TF_0.11 (0.00s)
    --- PASS: TestConvert/instance/TF_0.11 (0.00s)
    --- PASS: TestConvert/bucket/TF_0.11 (0.00s)
    --- PASS: TestConvert/sql/TF_0.11 (0.00s)
    --- PASS: TestConvert/firewall/TF_0.11#01 (0.00s)
    --- PASS: TestConvert/validate/always_violate/TF_0.11 (1.17s)
    --- PASS: TestConvert/disk/TF_0.12 (0.00s)
    --- PASS: TestConvert/project/TF_0.12 (0.00s)
    --- PASS: TestConvert/project_billing_info/TF_0.12 (0.00s)
    --- PASS: TestConvert/firewall/TF_0.12 (0.00s)
    --- PASS: TestConvert/instance/TF_0.12 (0.00s)
    --- PASS: TestConvert/bucket/TF_0.12 (0.00s)
    --- PASS: TestConvert/sql/TF_0.12 (0.00s)
    --- PASS: TestConvert/firewall/TF_0.12#01 (0.00s)
    --- PASS: TestConvert/validate/always_violate/TF_0.12 (1.08s)
PASS
ok  	github.com/GoogleCloudPlatform/terraform-validator/test	9.056s
```

**Pull request merged**
