### PR TITLE
[WIP] Move ancestry logic upstream

### PR DESCRIPTION
**Pull request by nstogner**
Relies on https://github.com/GoogleCloudPlatform/magic-modules/pull/1620.

Addresses #4 & #5.

### CODE REVIEW

**Comment by AdrienWalkowiak** [comment]
I think this is related to an issue I am having with the target in my constraint for projects. It works well for other resources, but for projects to be correctly targeted by my constraint, I have to use oragnization/* as a target... Nothing else works.

Is there anything I can do to help merge this PR?

**Comment by morgante** [comment]
@AdrienWalkowiak Would you be able to pick up working on https://github.com/GoogleCloudPlatform/magic-modules/pull/1620? @nstogner is no longer working on this project, so we just need someone to take over the PR.

**Comment by yukinying** [comment]
Given that the upstream pull request is closed without being merged, should this pull request be closed as well?

**Comment by morgante** [comment]
Yes, I think this can be closed but I'd still like to upstream mappers: #103.

**Pull request closed without merging**
