### PR TITLE
Removed vendored dependencies

### PR DESCRIPTION
**Pull request by melinath**
They are no longer in use on the gcp provider for terraform, and are harder to deal with than non-vendored dependencies, since they require regular non-reviewable PRs.

Related to #158

---

My understanding is that we want to move away from vendored dependencies, but that's not based on anything super specific, other than that vendoring seems to be an older mechanism that has been phased out in the provider code. I'd love to know what your thoughts are!

Because of the drift introduced in #157, this leaves in place the tgc vendored code via a `replace` statement.

### CODE REVIEW

**Comment by morgante** [comment]
I'm not sure if this is the best practice or not? For libraries it makes sense, but for a binary having the guarantee of always being able to build if needed seems important.

In either case we definitely would need to address [this drift](https://github.com/GoogleCloudPlatform/terraform-validator/pull/157#issuecomment-735921150) before removing the vendor/ directory.

**Comment by melinath** [comment]
@morgante sorry for the ping; I had briefly assigned you prior to the tests failing. As you mention, there's drift in the repo that makes removing the vendoring at this time infeasible. Based on discussion with the team, it sounds like we would like to remove the vendoring in the long run; however, I'm not sure if that's our decision to make or not?

**Comment by melinath** [comment]
although actually I guess we could remove vendoring and use a `replace` directive to keep the drifted version of tgc for the moment.

**Comment by morgante** [comment]
> Based on discussion with the team, it sounds like we would like to remove the vendoring in the long run; however, I'm not sure if that's our decision to make or not?

It's ultimately a decision for your team. My main question would be how confident you are in being able to rebuild at will without vendoring?

**Comment by melinath** [comment]
@rileykarson My take on this would be that it sounds like go is now sufficiently mature that there's less worry of things suddenly disappearing? But you'd be more familiar with that than I am.

Removing vendoring would definitely have the benefit of preventing manual drift introduced in vendored dependencies.

**Review by rileykarson — APPROVED** [review]
Go Modules has a module cache, which means disappearing modules aren't a big deal imo.

**Review by rileykarson — APPROVED** [review]
Go Modules has a module cache, which means disappearing modules aren't a big deal imo.

**Pull request merged**
